#!/usr/bin/env bash

################################################################
# Copyright (c) 2021 Witalis Domitrz <witekdomitrz@gmail.com>
# MIT License
################################################################

set -e

if [ "$#" -ne 1 ]; then
    echo "One argument expected [user@]host[:dir]"
    exit 1
fi

scp_path="$1"
# Split scp_path by ":" to get [user@]host and dir.
IFS=":" read -r host dir <<<"${scp_path}"
# Reassign scp_path to ensure that it has ":".
scp_path="$host:$dir"

# Create directory in which the remote directory will be mounted.
tempdir="$(mktemp --directory)"

# Mount the remote directory and get there.
sshfs "${scp_path}" "${tempdir}"
cd "${tempdir}"
# Set the command to run terminal remotely.
vim -c "let terminal_shell = \"ssh \\\"${host}\\\" -t \'cd \\\"${dir}\\\" \; exec \\\"\$SHELL\\\" -il\'\""
# After vim terminated, go back to the previous directory.
cd - >/dev/null
# Umount the remote directory and remove the mount point.
fusermount -u "${tempdir}"
rmdir "${tempdir}"
